<?php

namespace BlogBundle\Repository;

/**
 * CoursPlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursPlanningRepository extends \Doctrine\ORM\EntityRepository
{
}
